version: "3.0"
services:
  canada:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.server.config.DevelopmentConfig
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      - redis
    command: python ./canadaAps/rentCanada.py
  celery:
    build: .
    volumes:
      - .:/code
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.server.config.DevelopmentConfig
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - canada
      - redis
    command: celery --app canadaAps.rentCanada worker --loglevel=info
  redis:
    image: redis:6-alpine